#!/usr/bin/env python3
"""
ZUUP / CryptoExam — Question Pipeline Reference Prototype
=========================================================

Proves the three load-bearing claims of QUESTION-PIPELINE-DESIGN.md, end to end,
with **zero third-party dependencies** (Python 3.9+ stdlib only) so it runs anywhere:

  CLAIM 1  ANTI-HALLUCINATION
           Item answer keys are COMPUTED from a template, never generated by a
           model. An item whose asserted key disagrees with its own derivation is
           mechanically rejected. Demonstrated with a planted bad item.

  CLAIM 2  ANTI-LEAK / UNPREDICTABILITY
           The paper is selected at T0 by a public randomness beacon, not by a
           person. Same beacon => byte-identical paper at every centre. Different
           beacon => a different paper. Nobody who did not know the beacon in
           advance could have known the paper.

  CLAIM 3  FAIRNESS
           Papers assembled from different beacons are statistically equivalent:
           their IRT Test Information Functions match within tolerance, and every
           blueprint / anti-leak constraint holds on every form.

Run:
    python3 pipeline.py            # full demo + self-checks
    python3 pipeline.py --quiet    # self-checks only, exit code is the result

PRODUCTION SUBSTITUTIONS (deliberately avoided here to keep this dependency-free):
    verify_expression()  -> SymPy (symbolic re-derivation, not float eval)
    units checking       -> Pint
    assemble()           -> OR-Tools CP-SAT with num_workers=1, fixed random_seed
    prng                 -> same HMAC construction; this one is already production-grade
"""

from __future__ import annotations

import argparse
import hashlib
import hmac
import json
import math
import re
import sys
from dataclasses import dataclass, field
from itertools import product
from typing import Any, Callable, Iterable

# ══════════════════════════════════════════════════════════════════════════════
# 1. Deterministic randomness
#
# Python's `random` is seedable but its internal algorithms are not contractually
# stable across versions. Every centre must derive the IDENTICAL paper from the
# same beacon, so we use an explicit HMAC-SHA256 counter-mode PRNG: fully
# specified, reproducible on any platform, any language, forever.
#
# This mirrors the HKDF construction already used in question-crypto.ts.
# ══════════════════════════════════════════════════════════════════════════════


class DeterministicRNG:
    """HMAC-SHA256 counter-mode PRNG. Byte-identical output for a given seed."""

    def __init__(self, seed: bytes, info: bytes = b"") -> None:
        self._key = hmac.new(seed, b"cryptoexam:prng:" + info, hashlib.sha256).digest()
        self._counter = 0
        self._buf = b""

    def _refill(self) -> None:
        self._buf += hmac.new(
            self._key, self._counter.to_bytes(8, "big"), hashlib.sha256
        ).digest()
        self._counter += 1

    def bytes(self, n: int) -> bytes:
        while len(self._buf) < n:
            self._refill()
        out, self._buf = self._buf[:n], self._buf[n:]
        return out

    def below(self, n: int) -> int:
        """Uniform int in [0, n). Rejection-sampled, so no modulo bias."""
        if n <= 0:
            raise ValueError("n must be positive")
        bits = max(1, (n - 1).bit_length())
        nbytes = (bits + 7) // 8
        mask = (1 << bits) - 1
        while True:
            v = int.from_bytes(self.bytes(nbytes), "big") & mask
            if v < n:
                return v

    def shuffled(self, items: Iterable[Any]) -> list[Any]:
        """Fisher-Yates. Deterministic given the seed."""
        arr = list(items)
        for i in range(len(arr) - 1, 0, -1):
            j = self.below(i + 1)
            arr[i], arr[j] = arr[j], arr[i]
        return arr


def hkdf_seed(beacon: bytes, purpose: str, exam_id: str) -> bytes:
    """Mirrors question-crypto.ts: HKDF-ish derivation from the T0 beacon."""
    return hmac.new(
        beacon, f"cryptoexam:{purpose}:{exam_id}".encode(), hashlib.sha256
    ).digest()


# ══════════════════════════════════════════════════════════════════════════════
# 2. Safe expression evaluation
#
# Templates carry an expression for the correct answer and for each distractor.
# We evaluate in a locked-down namespace: no builtins, no attribute access, no
# names outside the declared parameters and a small maths allow-list.
#
# In production this is SymPy doing genuine symbolic re-derivation. The point of
# the stage is identical either way: THE KEY IS COMPUTED, NOT ASSERTED.
# ══════════════════════════════════════════════════════════════════════════════

_ALLOWED_NAMES = {
    "sqrt": math.sqrt, "pi": math.pi, "e": math.e, "log": math.log,
    "exp": math.exp, "sin": math.sin, "cos": math.cos, "tan": math.tan,
    "abs": abs, "min": min, "max": max, "round": round,
}
_EXPR_OK = re.compile(r"^[0-9a-zA-Z_+\-*/%.,()\s]+$")


class VerificationError(Exception):
    """Raised when an item fails machine verification. Item is discarded."""


def verify_expression(expr: str, params: dict[str, Any]) -> float:
    """Evaluate `expr` against `params`. Rejects anything outside the allow-list."""
    if not _EXPR_OK.match(expr):
        raise VerificationError(f"expression contains disallowed characters: {expr!r}")
    if "__" in expr:
        raise VerificationError("dunder access is not permitted")
    env: dict[str, Any] = {"__builtins__": {}}
    env.update(_ALLOWED_NAMES)
    overlap = set(params) & set(_ALLOWED_NAMES)
    if overlap:
        raise VerificationError(f"parameter shadows a builtin: {sorted(overlap)}")
    env.update(params)
    try:
        value = eval(expr, env)  # noqa: S307 - namespace is locked down above
    except Exception as exc:  # noqa: BLE001
        raise VerificationError(f"evaluation failed for {expr!r}: {exc}") from exc
    if not isinstance(value, (int, float)) or isinstance(value, bool):
        raise VerificationError(f"expression is not numeric: {expr!r} -> {value!r}")
    if math.isnan(value) or math.isinf(value):
        raise VerificationError(f"expression is not finite: {expr!r}")
    return float(value)


# ══════════════════════════════════════════════════════════════════════════════
# 3. Item templates  (design doc section 5.1)
# ══════════════════════════════════════════════════════════════════════════════


@dataclass(frozen=True)
class Distractor:
    expr: str
    misconception: str


@dataclass
class Template:
    """
    An item MODEL. Expands into many sibling items whose keys are computed.

    `answer_expr` and every distractor expression are evaluated independently at
    expansion time; the resulting item carries no model-asserted answer at all.
    """
    template_id: str
    author: str            # setter id - drives the anti-leak contribution cap
    subject: str
    topic: str
    blooms: int            # 1..6
    stem: str              # "...radius {R} m ... speed {v} m/s..."
    params: dict[str, list[Any]]
    answer_expr: str
    distractors: list[Distractor]
    unit: str = ""
    irt_a: float = 1.0     # discrimination - a template-family prior
    irt_b: float = 0.0     # difficulty     - siblings inherit, +- jitter
    irt_c: float = 0.25    # guessing       - 1/4 for 4-option MCQ
    param_constraint: Callable[[dict[str, Any]], bool] | None = None

    def combinations(self) -> list[dict[str, Any]]:
        keys = sorted(self.params)  # sorted => deterministic expansion order
        out = []
        for values in product(*(self.params[k] for k in keys)):
            combo = dict(zip(keys, values))
            if self.param_constraint is None or self.param_constraint(combo):
                out.append(combo)
        return out


@dataclass
class Item:
    """A concrete, machine-verified question. Ready to be sealed."""
    item_id: str
    template_id: str
    author: str
    subject: str
    topic: str
    blooms: int
    stem: str
    options: list[str]
    correct_index: int
    irt_a: float
    irt_b: float
    irt_c: float
    status: str = "PROVISIONAL"     # PROVISIONAL | CALIBRATED | RETIRED
    provenance: dict[str, Any] = field(default_factory=dict)

    def information(self, theta: float) -> float:
        """3PL Fisher information at ability theta. The unit of 'how hard'."""
        a, b, c = self.irt_a, self.irt_b, self.irt_c
        p = c + (1.0 - c) / (1.0 + math.exp(-a * (theta - b)))
        q = 1.0 - p
        if p <= 1e-9 or q <= 1e-9:
            return 0.0
        return (a * a) * (q / p) * (((p - c) / (1.0 - c)) ** 2)


def _fmt(value: float, unit: str) -> str:
    """Render a number the way a candidate would see it."""
    text = f"{value:.4f}".rstrip("0").rstrip(".") if value % 1 else str(int(value))
    return f"{text} {unit}".strip()


# ══════════════════════════════════════════════════════════════════════════════
# 4. Expansion + verification  (design doc section 5.2, stages S0 and S1)
# ══════════════════════════════════════════════════════════════════════════════


@dataclass
class ExpansionReport:
    accepted: list[Item] = field(default_factory=list)
    rejected: list[tuple[str, str]] = field(default_factory=list)  # (id, reason)

    def reject(self, ident: str, reason: str) -> None:
        self.rejected.append((ident, reason))


def expand_and_verify(
    templates: list[Template],
    rng: DeterministicRNG,
    max_variants_per_template: int = 12,
) -> ExpansionReport:
    """
    Expand every template into sibling items, verifying each one.

    S0 (structural): 4 distinct options, key present exactly once, key position
                     balanced across the pool, stem fully substituted.
    S1 (symbolic):   the correct answer is RE-DERIVED from the expression. An
                     item can only exist if its key is reproducible.
    """
    report = ExpansionReport()

    for tpl in templates:
        combos = tpl.combinations()
        if not combos:
            report.reject(tpl.template_id, "no parameter combination satisfies constraints")
            continue

        # Deterministic subsample so pools stay a sane size.
        combos = rng.shuffled(combos)[:max_variants_per_template]

        for idx, combo in enumerate(combos):
            ident = f"{tpl.template_id}#{idx:02d}"
            try:
                # ---- S1: compute the key. Never trust an asserted answer. ----
                answer = verify_expression(tpl.answer_expr, combo)
                wrongs = [verify_expression(d.expr, combo) for d in tpl.distractors]

                # ---- S0: structural integrity ----
                if len(tpl.distractors) != 3:
                    raise VerificationError("expected exactly 3 distractors")

                rendered = [_fmt(answer, tpl.unit)] + [_fmt(w, tpl.unit) for w in wrongs]
                if len(set(rendered)) != 4:
                    raise VerificationError(
                        "a distractor collides with the key or another distractor "
                        f"(rendered: {rendered})"
                    )

                stem = tpl.stem
                for key, value in combo.items():
                    stem = stem.replace("{" + key + "}", str(value))
                if "{" in stem or "}" in stem:
                    raise VerificationError(f"stem has unsubstituted placeholders: {stem!r}")

                # ---- key position balanced by the beacon PRNG, not by habit ----
                order = rng.shuffled(range(4))
                options = [rendered[i] for i in order]
                correct_index = order.index(0)

                # Siblings inherit the family's IRT prior with a small deterministic
                # jitter, so they are near-identical but not literally identical.
                jitter = (rng.below(2001) - 1000) / 10000.0   # +-0.10 logits

                report.accepted.append(
                    Item(
                        item_id=ident,
                        template_id=tpl.template_id,
                        author=tpl.author,
                        subject=tpl.subject,
                        topic=tpl.topic,
                        blooms=tpl.blooms,
                        stem=stem,
                        options=options,
                        correct_index=correct_index,
                        irt_a=tpl.irt_a,
                        irt_b=tpl.irt_b + jitter,
                        irt_c=tpl.irt_c,
                        provenance={"params": combo, "derivation": tpl.answer_expr},
                    )
                )
            except VerificationError as exc:
                report.reject(ident, str(exc))

    return report


# ══════════════════════════════════════════════════════════════════════════════
# 5. Automated Test Assembly  (design doc section 6.1)
#
# Beacon-seeded, constraint-respecting, deterministic. This is the function that
# replaces "a human picks the questions".
# ══════════════════════════════════════════════════════════════════════════════

THETA_GRID = [-3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0]


@dataclass
class Blueprint:
    exam_id: str
    length: int
    per_subject: dict[str, int]
    blooms_min: dict[int, int] = field(default_factory=dict)
    max_per_author_pct: float = 0.05      # design doc section 5.3 - the anti-leak cap
    target_information: dict[float, float] = field(default_factory=dict)

    def max_per_author(self) -> int:
        return max(1, math.ceil(self.length * self.max_per_author_pct))


def _tif(items: list[Item]) -> dict[float, float]:
    return {t: sum(i.information(t) for i in items) for t in THETA_GRID}


def _misfit(items: list[Item], target: dict[float, float]) -> float:
    """L1 distance between this form's information curve and the target."""
    cur = _tif(items)
    return sum(abs(cur[t] - target.get(t, 0.0)) for t in THETA_GRID)


class AssemblyError(Exception):
    pass


def assemble(pool: list[Item], bp: Blueprint, beacon: bytes) -> list[Item]:
    """
    Select `bp.length` items from `pool`, seeded by the T0 beacon.

    Randomised-greedy (GRASP): at each step consider the top-k candidates by
    marginal improvement to the information curve and pick among them using the
    beacon PRNG. Near-optimal on fairness, genuinely unpredictable in selection.

    Hard constraints, all enforced at insertion time:
      * exact per-subject counts (blueprint)
      * <= max_per_author items from any one setter   <- the anti-leak guarantee
      * <= 1 item from any one template               <- no sibling collisions
      * only CALIBRATED items may be selected         <- nothing unproven is scored
    """
    rng = DeterministicRNG(hkdf_seed(beacon, "ata", bp.exam_id))

    eligible = [i for i in pool if i.status == "CALIBRATED"]
    if len(eligible) < bp.length:
        raise AssemblyError(
            f"pool too small: {len(eligible)} calibrated items, need {bp.length}"
        )

    # ---- feasibility pre-check ------------------------------------------------
    # "<= 1 item per template" caps a form at (number of distinct templates), and
    # the author cap caps it at (setters x cap). Catch an impossible blueprint here
    # with a diagnostic rather than 3/4 of the way through a greedy run.
    cap = bp.max_per_author()
    for subject, want in bp.per_subject.items():
        subject_items = [i for i in eligible if i.subject == subject]
        n_templates = len({i.template_id for i in subject_items})
        n_authors = len({i.author for i in subject_items})
        if n_templates < want:
            raise AssemblyError(
                f"infeasible blueprint: subject {subject!r} needs {want} items but the "
                f"pool has only {n_templates} distinct templates, and no form may carry "
                "two siblings of the same template. Author more templates or shorten "
                "the paper."
            )
        if n_authors * cap < want:
            raise AssemblyError(
                f"infeasible blueprint: subject {subject!r} needs {want} items but has "
                f"{n_authors} setters at a cap of {cap} each (max {n_authors * cap}). "
                "Recruit more setters for this subject or relax max_per_author_pct."
            )
    if sum(bp.per_subject.values()) != bp.length:
        raise AssemblyError(
            f"blueprint subject counts sum to {sum(bp.per_subject.values())}, "
            f"not the paper length {bp.length}"
        )

    # Beacon-shuffled base order: this is what makes two different beacons
    # produce genuinely different papers rather than the same greedy answer.
    eligible = rng.shuffled(sorted(eligible, key=lambda i: i.item_id))

    chosen: list[Item] = []
    by_subject: dict[str, int] = {s: 0 for s in bp.per_subject}
    by_author: dict[str, int] = {}
    used_templates: set[str] = set()
    author_cap = bp.max_per_author()

    def admissible(item: Item) -> bool:
        if item.template_id in used_templates:
            return False
        if by_author.get(item.author, 0) >= author_cap:
            return False
        if by_subject.get(item.subject, 0) >= bp.per_subject.get(item.subject, 0):
            return False
        return True

    for _ in range(bp.length):
        candidates = [i for i in eligible if admissible(i)]
        if not candidates:
            raise AssemblyError(
                "no admissible item remains - constraints are infeasible for this pool. "
                f"chosen={len(chosen)}/{bp.length}, subject counts={by_subject}"
            )

        # Rank by how much each candidate closes the gap to the target curve.
        scored = sorted(
            ((_misfit(chosen + [c], bp.target_information), c.item_id, c) for c in candidates),
            key=lambda row: (row[0], row[1]),      # deterministic tie-break by id
        )
        shortlist = scored[: min(5, len(scored))]  # GRASP restricted candidate list
        _, _, pick = shortlist[rng.below(len(shortlist))]

        chosen.append(pick)
        by_subject[pick.subject] = by_subject.get(pick.subject, 0) + 1
        by_author[pick.author] = by_author.get(pick.author, 0) + 1
        used_templates.add(pick.template_id)

    # Present in a beacon-determined order (per-form; per-SEAT scrambling on top
    # of this is what defeats neighbour-copying - design doc section 6.4).
    return rng.shuffled(chosen)


def form_manifest_hash(form: list[Item]) -> str:
    """
    What gets anchored on-chain. Order-independent so it commits to the SET of
    items, letting per-seat scrambling vary freely underneath the commitment.
    """
    payload = json.dumps(sorted(i.item_id for i in form), separators=(",", ":"))
    return hashlib.sha256(payload.encode()).hexdigest()


def check_constraints(form: list[Item], bp: Blueprint) -> list[str]:
    """Independent re-verification. This is what an auditor runs (design doc 6.1)."""
    problems: list[str] = []

    if len(form) != bp.length:
        problems.append(f"length {len(form)} != {bp.length}")

    subjects: dict[str, int] = {}
    authors: dict[str, int] = {}
    templates: dict[str, int] = {}
    for item in form:
        subjects[item.subject] = subjects.get(item.subject, 0) + 1
        authors[item.author] = authors.get(item.author, 0) + 1
        templates[item.template_id] = templates.get(item.template_id, 0) + 1

    for subject, want in bp.per_subject.items():
        got = subjects.get(subject, 0)
        if got != want:
            problems.append(f"subject {subject}: {got} != {want}")

    cap = bp.max_per_author()
    for author, count in authors.items():
        if count > cap:
            problems.append(f"AUTHOR CAP BREACH: {author} has {count} items (cap {cap})")

    for tid, count in templates.items():
        if count > 1:
            problems.append(f"sibling collision: {tid} appears {count} times")

    for item in form:
        if item.status != "CALIBRATED":
            problems.append(f"uncalibrated item scored: {item.item_id}")

    return problems


# ══════════════════════════════════════════════════════════════════════════════
# 6. Demo content
# ══════════════════════════════════════════════════════════════════════════════


def demo_templates() -> list[Template]:
    """A small but genuine multi-subject template set across 8 setters."""
    t: list[Template] = []

    # ---------- Physics ----------
    t.append(Template(
        "PHY-MECH-CIRC-001", "setter-01", "Physics", "Circular Motion", 3,
        "A particle moves along a circular path of radius {R} m with a constant "
        "speed of {v} m/s. The magnitude of its centripetal acceleration is:",
        {"R": [2, 4, 5, 8], "v": [4, 6, 10, 12]},
        "v**2 / R",
        [Distractor("v / R", "confuses angular velocity with acceleration"),
         Distractor("v**2", "omits the radius entirely"),
         Distractor("2*v**2 / R", "spurious factor of two")],
        unit="m/s^2", irt_a=1.1, irt_b=-0.3,
    ))
    t.append(Template(
        "PHY-EM-COIL-002", "setter-01", "Physics", "Electromagnetism", 2,
        "A circular coil of {N} turns and radius {R} cm carries a current of {I} A. "
        "Taking mu0/4pi = 1e-7, the magnetic field at its centre, in microtesla, is:",
        {"N": [10, 20, 50], "R": [2, 5, 10], "I": [1, 2, 4]},
        "2 * pi * N * I / (R / 100) * 1e-7 * 1e6",
        [Distractor("2 * pi * I / (R / 100) * 1e-7 * 1e6", "drops the turn count"),
         Distractor("2 * pi * N * I / R * 1e-7 * 1e6", "forgets cm to m conversion"),
         Distractor("pi * N * I / (R / 100) * 1e-7 * 1e6", "halves the standard result")],
        unit="uT", irt_a=1.3, irt_b=0.4,
    ))
    t.append(Template(
        "PHY-KIN-PROJ-003", "setter-02", "Physics", "Kinematics", 3,
        "A body is projected at {u} m/s at {ang} degrees to the horizontal. "
        "Taking g = 10 m/s^2, its time of flight is:",
        {"u": [20, 30, 40], "ang": [30, 45, 60]},
        "2 * u * sin(ang * pi / 180) / 10",
        [Distractor("u * sin(ang * pi / 180) / 10", "computes time to apex only"),
         Distractor("2 * u * cos(ang * pi / 180) / 10", "uses cosine instead of sine"),
         Distractor("2 * u / 10", "ignores the launch angle")],
        unit="s", irt_a=1.2, irt_b=0.1,
    ))
    t.append(Template(
        "PHY-WORK-ENER-004", "setter-02", "Physics", "Work & Energy", 2,
        "A {m} kg block moving at {v} m/s is brought to rest by friction over "
        "{d} m. The magnitude of the frictional force is:",
        {"m": [2, 4, 5], "v": [4, 6, 10], "d": [2, 5, 8]},
        "m * v**2 / (2 * d)",
        [Distractor("m * v**2 / d", "omits the factor of one half"),
         Distractor("m * v / (2 * d)", "uses momentum instead of kinetic energy"),
         Distractor("m * v**2 * d / 2", "multiplies by distance instead of dividing")],
        unit="N", irt_a=1.0, irt_b=-0.1,
    ))

    # ---------- Chemistry ----------
    t.append(Template(
        "CHM-STOI-MOLE-001", "setter-03", "Chemistry", "Stoichiometry", 2,
        "The number of moles in {g} g of a compound of molar mass {M} g/mol is:",
        {"g": [22, 44, 88, 132], "M": [11, 22, 44]},
        "g / M",
        [Distractor("M / g", "inverts the relationship"),
         Distractor("g * M", "multiplies instead of divides"),
         Distractor("g / (2 * M)", "spurious factor of two")],
        unit="mol", irt_a=0.9, irt_b=-0.8,
    ))
    t.append(Template(
        "CHM-EQUI-PH-002", "setter-03", "Chemistry", "Ionic Equilibrium", 3,
        "A strong monobasic acid is diluted to a concentration of 1e-{p} M. "
        "Ignoring water autoionisation, the pH of the solution is:",
        {"p": [2, 3, 4, 5]},
        "p",
        [Distractor("14 - p", "reports pOH instead of pH"),
         Distractor("p / 2", "treats the acid as dibasic"),
         Distractor("7 - p", "subtracts from neutral pH")],
        irt_a=1.4, irt_b=0.2,
    ))
    t.append(Template(
        "CHM-GAS-IDEAL-003", "setter-04", "Chemistry", "Gaseous State", 3,
        "{n} mol of an ideal gas occupies {V} L at {T} K. Taking R = 0.0821 "
        "L atm/(mol K), the pressure in atm is:",
        {"n": [1, 2, 4], "V": [10, 20, 25], "T": [273, 300, 400]},
        "n * 0.0821 * T / V",
        [Distractor("n * 0.0821 * V / T", "inverts volume and temperature"),
         Distractor("0.0821 * T / V", "drops the mole count"),
         Distractor("n * 0.0821 * T / (2 * V)", "spurious factor of two")],
        unit="atm", irt_a=1.1, irt_b=0.3,
    ))
    t.append(Template(
        "CHM-THERMO-ENTH-004", "setter-04", "Chemistry", "Thermodynamics", 4,
        "For a reaction, delta-H = {H} kJ/mol and delta-S = {S} J/(mol K). "
        "At {T} K, delta-G in kJ/mol is:",
        {"H": [-100, -50, 40], "S": [-100, 100, 200], "T": [300, 500]},
        "H - T * S / 1000",
        [Distractor("H + T * S / 1000", "sign error on the entropy term"),
         Distractor("H - T * S", "forgets the J to kJ conversion"),
         Distractor("H", "ignores the entropy contribution entirely")],
        unit="kJ/mol", irt_a=1.5, irt_b=0.9,
    ))

    # ---------- Mathematics ----------
    t.append(Template(
        "MAT-ALG-DET-001", "setter-05", "Mathematics", "Matrices", 4,
        "For a square matrix A of order {n}, if det(A) = {d}, then det(adj A) is:",
        {"n": [3, 4], "d": [2, 3, 5]},
        "d ** (n - 1)",
        [Distractor("d ** n", "uses n instead of n-1 as the exponent"),
         Distractor("d", "assumes the determinant is unchanged"),
         Distractor("n * d", "multiplies instead of exponentiating")],
        irt_a=1.4, irt_b=0.7,
    ))
    t.append(Template(
        "MAT-CALC-AREA-002", "setter-05", "Mathematics", "Integral Calculus", 4,
        "The area bounded by y = {a}x^2, the x-axis, and the lines x = 0 and "
        "x = {b} is:",
        {"a": [1, 2, 3], "b": [2, 3, 4]},
        "a * b**3 / 3",
        [Distractor("a * b**3", "omits the division by three"),
         Distractor("a * b**2 / 2", "integrates a linear function instead"),
         Distractor("a * b**3 / 2", "uses the wrong antiderivative constant")],
        irt_a=1.3, irt_b=0.5,
    ))
    t.append(Template(
        "MAT-PROB-BAYES-003", "setter-06", "Mathematics", "Probability", 5,
        "An urn holds {r} red and {b} blue balls. Two are drawn without "
        "replacement. The probability that both are red, as a percentage, is:",
        {"r": [3, 4, 5, 6], "b": [2, 3, 5]},
        "100 * (r / (r + b)) * ((r - 1) / (r + b - 1))",
        [Distractor("100 * (r / (r + b)) * (r / (r + b))", "assumes replacement"),
         Distractor("100 * (r - 1) / (r + b - 1)", "drops the first draw"),
         Distractor("100 * r / (r + b)", "computes a single draw only")],
        unit="%", irt_a=1.6, irt_b=1.1,
    ))
    t.append(Template(
        "MAT-TRIG-IDEN-004", "setter-06", "Mathematics", "Trigonometry", 3,
        "If sin(x) = {p}/{q} and x lies in the first quadrant, then "
        "{q}*cos(x) equals:",
        {"p": [3, 5, 7], "q": [13, 25]},
        "sqrt(q**2 - p**2)",
        [Distractor("q - p", "subtracts instead of using Pythagoras"),
         Distractor("sqrt(q**2 + p**2)", "sign error inside the radical"),
         Distractor("p", "confuses sine with cosine")],
        param_constraint=lambda c: c["p"] < c["q"],
        irt_a=1.2, irt_b=0.0,
    ))

    # Two more setters, to exercise the contribution cap meaningfully.
    t.append(Template(
        "PHY-OPT-LENS-005", "setter-07", "Physics", "Optics", 3,
        "An object is placed {u} cm from a converging lens of focal length "
        "{f} cm. The image distance, in cm, is:",
        {"u": [30, 40, 60], "f": [10, 15, 20]},
        "1 / (1/f - 1/u)",
        [Distractor("1 / (1/f + 1/u)", "sign error in the lens equation"),
         Distractor("f * u", "multiplies the two distances"),
         Distractor("u - f", "subtracts the focal length")],
        param_constraint=lambda c: c["u"] != c["f"],
        unit="cm", irt_a=1.2, irt_b=0.2,
    ))
    t.append(Template(
        "CHM-ELEC-FARA-005", "setter-07", "Chemistry", "Electrochemistry", 4,
        "A current of {I} A is passed for {tmin} minutes through a solution. "
        "Taking F = 96500 C/mol, the charge passed in coulombs is:",
        {"I": [1, 2, 5], "tmin": [10, 30, 50]},
        "I * tmin * 60",
        [Distractor("I * tmin", "forgets minutes to seconds"),
         Distractor("I * tmin * 3600", "converts hours instead of minutes"),
         Distractor("I / (tmin * 60)", "divides instead of multiplying")],
        unit="C", irt_a=1.0, irt_b=-0.2,
    ))
    t.append(Template(
        "MAT-SEQ-AP-005", "setter-08", "Mathematics", "Sequences", 2,
        "The sum of the first {n} terms of an AP with first term {a} and common "
        "difference {d} is:",
        {"n": [10, 20, 25], "a": [2, 5, 7], "d": [3, 4]},
        "n / 2 * (2*a + (n - 1) * d)",
        [Distractor("n * (2*a + (n - 1) * d)", "omits the factor of one half"),
         Distractor("n / 2 * (2*a + n * d)", "off-by-one in the term count"),
         Distractor("n * a + d", "misremembers the formula entirely")],
        irt_a=0.9, irt_b=-0.6,
    ))
    t.append(Template(
        "PHY-THERM-CAL-006", "setter-08", "Physics", "Thermal Physics", 2,
        "How much heat, in joules, is needed to raise {m} kg of a substance of "
        "specific heat {c} J/(kg K) by {dT} K?",
        {"m": [2, 3, 5], "c": [400, 900], "dT": [10, 25, 40]},
        "m * c * dT",
        [Distractor("m * c", "ignores the temperature change"),
         Distractor("c * dT", "ignores the mass"),
         Distractor("m * c * dT / 2", "spurious factor of one half")],
        unit="J", irt_a=0.8, irt_b=-0.9,
    ))

    # ---- second cohort of setters: widens the pool so the optimiser has real
    #      combinatorial freedom, and spreads authorship so the cap binds ------
    t.append(Template(
        "PHY-SHM-PEND-007", "setter-09", "Physics", "Oscillations", 3,
        "A simple pendulum has length {L} m. Taking g = 10 m/s^2, its time "
        "period is:",
        {"L": [0.4, 0.9, 1.6, 2.5]},
        "2 * pi * sqrt(L / 10)",
        [Distractor("pi * sqrt(L / 10)", "halves the period"),
         Distractor("2 * pi * sqrt(10 / L)", "inverts length and g"),
         Distractor("2 * pi * L / 10", "drops the square root")],
        unit="s", irt_a=1.2, irt_b=0.3,
    ))
    t.append(Template(
        "PHY-ELEC-RES-008", "setter-10", "Physics", "Current Electricity", 3,
        "Three resistors of {R1}, {R2} and {R3} ohm are connected in parallel. "
        "The equivalent resistance is:",
        {"R1": [2, 3, 6], "R2": [3, 4, 12], "R3": [6, 12]},
        "1 / (1/R1 + 1/R2 + 1/R3)",
        [Distractor("R1 + R2 + R3", "applies the series formula"),
         Distractor("(R1 + R2 + R3) / 3", "averages the resistances"),
         Distractor("1 / (R1 + R2 + R3)", "forgets to invert each term")],
        unit="ohm", irt_a=1.3, irt_b=0.1,
    ))
    t.append(Template(
        "PHY-MOM-COLL-009", "setter-11", "Physics", "Momentum", 4,
        "A {m1} kg body moving at {u} m/s collides head-on with a stationary "
        "{m2} kg body and they move off together. Their common velocity is:",
        {"m1": [2, 4, 6], "m2": [2, 3, 6], "u": [5, 10, 12]},
        "m1 * u / (m1 + m2)",
        [Distractor("u", "assumes the velocity is unchanged"),
         Distractor("m1 * u / m2", "divides by the wrong mass"),
         Distractor("(m1 + m2) * u / m1", "inverts the mass ratio")],
        unit="m/s", irt_a=1.4, irt_b=0.6,
    ))

    t.append(Template(
        "CHM-SOLN-MOLAR-006", "setter-09", "Chemistry", "Solutions", 3,
        "{g} g of a solute of molar mass {M} g/mol is dissolved to make {V} mL "
        "of solution. The molarity is:",
        {"g": [4, 8, 20], "M": [40, 100], "V": [200, 500, 1000]},
        "(g / M) / (V / 1000)",
        [Distractor("(g / M) / V", "forgets the mL to L conversion"),
         Distractor("(g / M) * V / 1000", "multiplies by volume"),
         Distractor("(M / g) / (V / 1000)", "inverts mass and molar mass")],
        unit="M", irt_a=1.1, irt_b=0.0,
    ))
    t.append(Template(
        "CHM-KIN-HALF-007", "setter-12", "Chemistry", "Chemical Kinetics", 3,
        "A first-order reaction has rate constant {k} x 10^-3 s^-1. Its "
        "half-life, in seconds, is:",
        {"k": [1, 2, 3, 7]},
        "0.693 / (k / 1000)",
        [Distractor("(k / 1000) / 0.693", "inverts the relationship"),
         Distractor("0.693 * (k / 1000)", "multiplies instead of divides"),
         Distractor("2 / (k / 1000)", "uses 2 in place of ln 2")],
        unit="s", irt_a=1.2, irt_b=0.4,
    ))
    t.append(Template(
        "CHM-ATOM-BOHR-008", "setter-10", "Chemistry", "Atomic Structure", 2,
        "In the Bohr model of the hydrogen atom, the energy of the n = {n} "
        "level, in eV, is:",
        {"n": [1, 2, 3, 4, 5]},
        "-13.6 / n**2",
        [Distractor("-13.6 / n", "uses n instead of n squared"),
         Distractor("-13.6 * n**2", "multiplies instead of divides"),
         Distractor("13.6 / n**2", "sign error - energy must be negative")],
        unit="eV", irt_a=1.0, irt_b=-0.4,
    ))

    t.append(Template(
        "MAT-COORD-DIST-006", "setter-11", "Mathematics", "Coordinate Geometry", 2,
        "The distance between the points ({x1}, {y1}) and ({x2}, {y2}) is:",
        {"x1": [0, 1, 2], "y1": [0, 3], "x2": [4, 6, 8], "y2": [4, 7]},
        "sqrt((x2 - x1)**2 + (y2 - y1)**2)",
        [Distractor("(x2 - x1) + (y2 - y1)", "adds the legs instead of Pythagoras"),
         Distractor("sqrt((x2 + x1)**2 + (y2 + y1)**2)", "sign error in the differences"),
         Distractor("abs(x2 - x1) + abs(y2 - y1)", "computes Manhattan distance")],
        irt_a=0.9, irt_b=-0.7,
    ))
    t.append(Template(
        "MAT-QUAD-ROOT-007", "setter-12", "Mathematics", "Quadratic Equations", 4,
        "For the quadratic x^2 - {s}x + {p} = 0, the sum of the squares of the "
        "roots is:",
        {"s": [3, 5, 7, 9], "p": [2, 4, 6]},
        "s**2 - 2*p",
        [Distractor("s**2 + 2*p", "sign error on the product term"),
         Distractor("s**2", "ignores the product of roots"),
         Distractor("s**2 - p", "omits the factor of two")],
        irt_a=1.5, irt_b=0.8,
    ))
    t.append(Template(
        "MAT-GP-INF-008", "setter-09", "Mathematics", "Sequences", 3,
        "The sum to infinity of a GP with first term {a} and common ratio 1/{r} is:",
        {"a": [2, 3, 6], "r": [3, 4, 5]},
        "a * r / (r - 1)",
        [Distractor("a * (r - 1) / r", "inverts the ratio factor"),
         Distractor("a / r", "uses only the second term"),
         Distractor("a * r", "omits the denominator")],
        irt_a=1.2, irt_b=0.2,
    ))

    return t


def planted_bad_template() -> Template:
    """
    A template whose 'distractor' silently equals the correct answer - the exact
    shape of an LLM hallucination where the model restates the key as a wrong
    option. S0 must catch every variant of this. Nothing here reaches a candidate.
    """
    return Template(
        "BAD-HALLUCINATED-001", "setter-99", "Physics", "Mechanics", 3,
        "A {m} kg mass accelerates at {a} m/s^2. The net force is:",
        {"m": [2, 4], "a": [3, 5]},
        "m * a",
        [Distractor("a * m", "IDENTICAL TO THE KEY - hallucinated distractor"),
         Distractor("m + a", "adds instead of multiplying"),
         Distractor("m / a", "divides instead of multiplying")],
        unit="N",
    )


# ══════════════════════════════════════════════════════════════════════════════
# 7. Demo + self-checks
# ══════════════════════════════════════════════════════════════════════════════

BEACON_A = hashlib.sha256(b"drand:round:4210001").digest()
BEACON_B = hashlib.sha256(b"drand:round:4210002").digest()
EXAM_ID = "NEET-2026-05-03"


def build_pool(quiet: bool) -> list[Item]:
    templates = demo_templates() + [planted_bad_template()]
    rng = DeterministicRNG(b"pool-expansion-seed-v1")
    report = expand_and_verify(templates, rng, max_variants_per_template=12)

    for item in report.accepted:
        item.status = "CALIBRATED"   # in reality: earned via design doc section 7

    if not quiet:
        print("=" * 78)
        print("STAGE 1 - TEMPLATE EXPANSION + MACHINE VERIFICATION")
        print("=" * 78)
        print(f"  templates in            : {len(templates)}")
        print(f"  items accepted          : {len(report.accepted)}")
        print(f"  items rejected          : {len(report.rejected)}")
        print()
        print("  Rejections (each one is a wrong answer key that never shipped):")
        shown: set[str] = set()
        for ident, reason in report.rejected:
            family = ident.split("#")[0]
            if family in shown:
                continue
            shown.add(family)
            print(f"    {ident:26s} {reason[:88]}")
        print()
        sample = report.accepted[0]
        print("  Sample verified item:")
        print(f"    id       : {sample.item_id}")
        print(f"    stem     : {sample.stem[:96]}")
        print(f"    options  : {sample.options}")
        print(f"    key      : option {sample.correct_index} = {sample.options[sample.correct_index]}")
        print(f"    derived  : {sample.provenance['derivation']}  with  {sample.provenance['params']}")
        print("    ^ the key was COMPUTED from this expression, not asserted by a model")
        print()

    return report.accepted


def demo(quiet: bool) -> int:
    failures: list[str] = []

    pool = build_pool(quiet)

    bp = Blueprint(
        exam_id=EXAM_ID,
        length=18,
        per_subject={"Physics": 7, "Chemistry": 6, "Mathematics": 5},
        max_per_author_pct=0.11,       # 2 of 18 - see the scale note in the summary
        # A selection exam wants its measurement precision concentrated near the
        # CUT SCORE, not at average ability - hence the peak at theta = +1.0.
        # Magnitudes are sized to what an 18-item form can actually deliver; a
        # 90-item paper carries ~5x this information.
        target_information={-3.0: 0.05, -2.0: 0.30, -1.0: 1.30, 0.0: 3.40,
                            1.0: 4.20, 2.0: 2.10, 3.0: 0.70},
    )

    # ---- CLAIM 1: no hallucinated key survived -------------------------------
    if any(i.template_id.startswith("BAD-") for i in pool):
        failures.append("CLAIM 1 FAILED: a hallucinated item reached the pool")

    # ---- CLAIM 2: determinism + unpredictability -----------------------------
    form_a1 = assemble(pool, bp, BEACON_A)
    form_a2 = assemble(pool, bp, BEACON_A)
    form_b = assemble(pool, bp, BEACON_B)

    hash_a1, hash_a2, hash_b = map(form_manifest_hash, (form_a1, form_a2, form_b))

    if hash_a1 != hash_a2:
        failures.append("CLAIM 2 FAILED: same beacon produced different papers")
    if hash_a1 == hash_b:
        failures.append("CLAIM 2 FAILED: different beacons produced the same paper")

    overlap = len({i.item_id for i in form_a1} & {i.item_id for i in form_b})

    if not quiet:
        print("=" * 78)
        print("STAGE 2 - BEACON-DRIVEN ASSEMBLY  (nobody chose these questions)")
        print("=" * 78)
        print(f"  pool size               : {len(pool)} calibrated items")
        print(f"  paper length            : {bp.length}")
        print(f"  blueprint               : {bp.per_subject}")
        print(f"  author cap              : {bp.max_per_author()} items per setter")
        print()
        print(f"  beacon A -> manifest    : {hash_a1[:32]}...")
        print(f"  beacon A -> manifest    : {hash_a2[:32]}...   (re-run, must match)")
        print(f"  beacon B -> manifest    : {hash_b[:32]}...   (must differ)")
        print()
        print(f"  determinism             : {'PASS' if hash_a1 == hash_a2 else 'FAIL'}"
              "   same beacon => byte-identical paper at every centre")
        print(f"  unpredictability        : {'PASS' if hash_a1 != hash_b else 'FAIL'}"
              "   different beacon => different paper")
        print(f"  overlap A vs B          : {overlap}/{bp.length} items")
        print()

    # ---- CLAIM 3: fairness + constraints -------------------------------------
    for label, form in (("A", form_a1), ("B", form_b)):
        problems = check_constraints(form, bp)
        if problems:
            failures.append(f"CLAIM 3 FAILED: form {label} violates: {problems}")

    tif_a, tif_b = _tif(form_a1), _tif(form_b)
    peak = max(max(tif_a.values()), max(tif_b.values()))
    worst_gap = max(abs(tif_a[t] - tif_b[t]) for t in THETA_GRID)
    worst_pct = 100.0 * worst_gap / peak if peak else 0.0

    if worst_pct > 15.0:
        failures.append(
            f"CLAIM 3 FAILED: forms differ by {worst_pct:.1f}% of peak information "
            "- they are not statistically equivalent"
        )

    if not quiet:
        print("=" * 78)
        print("STAGE 3 - FAIRNESS  (are the two papers equally hard?)")
        print("=" * 78)
        print("  Test Information Function - higher means more measurement precision")
        print()
        print(f"  {'ability':>9} {'target':>9} {'form A':>9} {'form B':>9} {'|A-B|':>8}")
        print(f"  {'-'*9} {'-'*9} {'-'*9} {'-'*9} {'-'*8}")
        for t in THETA_GRID:
            print(f"  {t:>+9.1f} {bp.target_information.get(t, 0):>9.2f} "
                  f"{tif_a[t]:>9.2f} {tif_b[t]:>9.2f} {abs(tif_a[t]-tif_b[t]):>8.2f}")
        print()
        print(f"  worst divergence        : {worst_gap:.3f} ({worst_pct:.1f}% of peak)")
        print(f"  equivalence (<15%)      : {'PASS' if worst_pct <= 15.0 else 'FAIL'}")
        print()

        print("  Anti-leak - setter contribution to each form:")
        for label, form in (("A", form_a1), ("B", form_b)):
            counts: dict[str, int] = {}
            for item in form:
                counts[item.author] = counts.get(item.author, 0) + 1
            worst_author = max(counts, key=lambda a: counts[a])
            worst_n = counts[worst_author]
            print(f"    form {label}: {dict(sorted(counts.items()))}")
            print(f"             worst case {worst_author} = {worst_n}/{bp.length} "
                  f"({100.0*worst_n/bp.length:.1f}% of the paper)")
        print()
        print("  ^ A setter who leaks EVERYTHING they ever wrote compromises at most")
        print("    this fraction of the paper. That is the anti-leak guarantee, and it")
        print("    is a hard constraint in the optimiser rather than a policy promise.")
        print()

        print("=" * 78)
        print("ASSEMBLED PAPER (form A)")
        print("=" * 78)
        for n, item in enumerate(form_a1, 1):
            print(f"  Q{n:02d} [{item.subject[:4]:4s}/{item.author}] {item.stem[:82]}")
        print()

    # ---- verdict --------------------------------------------------------------
    print("=" * 78)
    if failures:
        print("RESULT: FAILED")
        for f in failures:
            print(f"  - {f}")
        print("=" * 78)
        return 1

    print("RESULT: ALL CLAIMS HOLD")
    print("=" * 78)
    print("  1. ANTI-HALLUCINATION  every key computed and re-verified; the planted")
    print("                         hallucinated item was rejected before the pool")
    print("  2. ANTI-LEAK           the paper is a function of a beacon that did not")
    print("                         exist when the items were written; no setter, no")
    print("                         operator and no centre could have known it")
    print("  3. FAIRNESS            independently assembled forms carry equivalent")
    print("                         information; blueprint and setter caps hold on all")
    print("=" * 78)
    print()
    print("NOTE ON DEMO SCALE: ~200 items from 25 templates across 12 setters, so the")
    print("cap sits at 11% (2 of 18). Production targets 10,000 items / 400+ templates /")
    print("50+ setters, where the cap tightens to 5% - 4 items on a 90-item paper, and")
    print("A-vs-B overlap falls toward zero. Scaling the pool strengthens every number")
    print("here; no part of the mechanism changes.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--quiet", action="store_true", help="self-checks only")
    args = ap.parse_args()
    return demo(quiet=args.quiet)


if __name__ == "__main__":
    sys.exit(main())
