/**
 * §30.1 print-kiosk unlock — the cross-language vector the port demanded.
 *
 * `print-unlock.ts` arrived with an explicit instruction in its own header:
 * generate shares in Python, reconstruct them here, assert equality, and do not
 * proceed past this test failing. That is the right instruction, because the two
 * implementations agree on the ALGORITHM and could still disagree on every
 * detail that matters — the field prime, the byte order used to turn a 32-byte
 * AES key into a field element, and whether the modular inverse is Fermat
 * (Python's `pow(d, PRIME-2, PRIME)`) or extended Euclid (this port's).
 *
 * The fixture is generated by the REAL public/backend implementation
 * (app/services/crypto/shamir_sss.py), not by hand, so this fails the moment the
 * two drift.
 *
 * Why it matters more here than usual: this is the fallback path for a centre
 * with NO connectivity window at T₀. If the reconstruction is subtly wrong, it
 * does not error — it returns a different 32-byte value, AES-GCM fails to open
 * the bundle, and the failure surfaces as "the paper is corrupt" in a rural
 * centre with no uplink and no way to diagnose it.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { deriveFromCachedBeacon, reconstructFromShards, unlockPrintMasterKey, type ShardPoint } from "../lib/print-unlock.ts";
import { deriveMasterSeed } from "../lib/question-seal.ts";
import { toHex } from "../lib/crypto.ts";

const here = dirname(fileURLToPath(import.meta.url));
const vector = JSON.parse(
  readFileSync(join(here, "fixtures", "shamir-crosslang.json"), "utf8"),
) as {
  prime_hex: string;
  known_key_hex: string;
  k: number;
  shares: { x: number; y_hex: string }[];
};

const shards = (idx: number[]): ShardPoint[] =>
  idx.map((i) => ({ x: vector.shares[i]!.x, y: BigInt(vector.shares[i]!.y_hex) }));

test("the TS port reconstructs a key that PYTHON split — the vector the header demanded", () => {
  const key = reconstructFromShards(shards([0, 1, 2]));
  assert.equal(toHex(key), vector.known_key_hex);
});

test("ANY k of the n shares reconstruct the same key", () => {
  // The whole point of a k-of-n scheme: which three officials turn up must not
  // matter. A port that only works for the first three would pass a naive test
  // and strand a centre whose Centre Admin is the one who is absent.
  for (const combo of [[0, 1, 2], [0, 2, 4], [1, 3, 4], [2, 3, 4]]) {
    assert.equal(toHex(reconstructFromShards(shards(combo))), vector.known_key_hex,
      `combination ${combo.join(",")} disagreed`);
  }
});

test("the reconstructed key is exactly 32 bytes, zero-padded on the left", () => {
  // The bigint loses leading zeros, and this vector's key starts with 0x00.
  // Without the pad the AES key would be 31 bytes and every open would fail.
  assert.equal(vector.known_key_hex.slice(0, 2), "00", "fixture must exercise the padding path");
  assert.equal(reconstructFromShards(shards([0, 1, 2])).length, 32);
});

test("fewer shares than the threshold do NOT reconstruct the key", () => {
  // Lagrange over 2 points of a degree-2 polynomial interpolates a DIFFERENT
  // value rather than failing, so the danger is a wrong key that looks like a
  // key. k-1 shares must not be enough, and must not silently look like enough.
  const two = reconstructFromShards(shards([0, 1]));
  assert.notEqual(toHex(two), vector.known_key_hex);
});

test("the field prime matches the Python side exactly", () => {
  // Everything else can be right and the whole scheme still wrong if the two
  // sides reduce modulo different primes.
  const key = reconstructFromShards(shards([0, 1, 2]));
  assert.equal(toHex(key), vector.known_key_hex);
  assert.equal(BigInt(vector.prime_hex).toString(16).length, 64);
});

test("unlock prefers a cached beacon and refuses when it has neither input", async () => {
  await assert.rejects(() => unlockPrintMasterKey(null, null), /cannot unlock/i);
  await assert.rejects(() => unlockPrintMasterKey(null, shards([0])), /cannot unlock/i);

  const viaShards = await unlockPrintMasterKey(null, shards([0, 1, 2]));
  assert.equal(viaShards.path, "shamir-local");
  assert.equal(toHex(viaShards.masterKey), vector.known_key_hex);
});

test("PATH A derives the SAME master seed as the CBT terminal, from the same inputs", async () => {
  // The print kiosk opens the very bundle question-seal.ts sealed, so agreeing
  // with that derivation is not a nicety — it is the difference between a
  // printed paper and 300 candidates in a rural centre looking at a decrypt
  // failure with no uplink to diagnose it.
  //
  // Asserted against the real function rather than a copied constant, so the
  // two cannot drift: change the scheme and this test changes with it.
  const beacon = new Uint8Array(32).fill(0xab);
  const hkdfSalt = new Uint8Array(16).fill(0x5a);
  const examId = "11111111-2222-3333-4444-555555555555";

  const viaCbt = await deriveMasterSeed(beacon, hkdfSalt, examId);
  const viaPrint = await deriveFromCachedBeacon({
    examId, drandRound: 1, beaconRandomness: beacon, hkdfSalt,
  });
  assert.equal(toHex(viaPrint), toHex(viaCbt));
});

test("a different exam id gives a different key from the same beacon", async () => {
  // Every centre gets the same public beacon. If the exam id did not bind into
  // the derivation, one centre's unlock would open another exam's paper.
  const beacon = new Uint8Array(32).fill(0xab);
  const hkdfSalt = new Uint8Array(16).fill(0x5a);
  const a = await deriveFromCachedBeacon({ examId: "exam-a", drandRound: 1, beaconRandomness: beacon, hkdfSalt });
  const b = await deriveFromCachedBeacon({ examId: "exam-b", drandRound: 1, beaconRandomness: beacon, hkdfSalt });
  assert.notEqual(toHex(a), toHex(b));
});
